version: '3.4'
services:
            
    doctrine:
        container_name: doctrine
        build:
            context: .
            dockerfile: Dockerfile-app
        ports:
            - "8080:80"
        volumes:
            - "../source/:/var/www/html/"
            - "../../cache-composer/:/root/.composer/"
        networks:
            - doctrine
        
networks:
    doctrine:
        driver: bridge
